# Generated by Django 4.2.2 on 2023-07-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("current_chapter", models.IntegerField(default=1)),
                ("at_boss_card", models.BooleanField(default=False)),
                ("game_beaten", models.BooleanField(default=False)),
                ("game_lost", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="players", to="character.player"
                    ),
                ),
            ],
        ),
    ]
