# Generated by Django 4.2.2 on 2023-07-02 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="dexterity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="magic",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="strength",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ]
            ),
        ),
    ]
