# Generated by Django 4.2.2 on 2023-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0002_alter_character_dexterity_alter_character_magic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="dexterity",
            field=models.IntegerField(
                choices=[(4, "Strong"), (3, "Average"), (1, "Weak")]
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="magic",
            field=models.IntegerField(
                choices=[(4, "Strong"), (3, "Average"), (1, "Weak")]
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="strength",
            field=models.IntegerField(
                choices=[(4, "Strong"), (3, "Average"), (1, "Weak")]
            ),
        ),
    ]
